### ISSUE TITLE
Viewer is not showing anything if the state machine is invalid

### ISSUE THREAD

**Issue by reinzor** [uleroboticsgroup/yasmin#28]
# Reproduce

- Create a state machine with invalid transitions
- Run viewer
- Open javascript console log, you will see an error 

# Expected result

Now the viewer is not showing anything, a proper error message would be appropriate.

**Comment by mgonzs13** [comment]
What do you think about validating the state machine before publishing the data [ac1c6745383f5eeb804385ecf903927005b4e0d4](https://github.com/uleroboticsgroup/yasmin/commit/ac1c6745383f5eeb804385ecf903927005b4e0d4#diff-abb8a3b1a49ff897eae3e9348ccc8287443ecc5c1475d206d5c8d901ffbc9e53R109) instead of doing it in the web viewer?

**Comment by reinzor** [comment]
This is definitely where it is supposed to be. However, viewer still shouldn't crash. Although, this situation should not occur anymore in a normal flow.

**Comment by mgonzs13** [comment]
Fixed in https://github.com/uleroboticsgroup/yasmin/commit/198e7e779d9ba75b249233e5a2bdd85110e5e689 by checking if all created edges have existing nodes. Thus, the viewer will not crash and show if the state machine is malformed.

**Comment by reinzor** [comment]
Nice, this can be closed then.
